version: '2.2'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kmb123
      POSTGRES_DB: postgres
      POSTGRES_SCHEMA: public
      POSTGRES_SCHEMA: disable
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kmb123
      POSTGRES_DB: mekari
